### ISSUE TITLE
Dataset not publicly available anymore?

### ISSUE THREAD

**Issue by akskuchi** [GT-Vision-Lab/abstract_scenes_v002#4]
Hello, the links on README doesn't seem to work anymore. Is the source relocated?

**Comment by StanislawAntol** [comment]
Hi Aditya,

It looks like my VT computer account was recently deleted, thus I didn't have access to what I used to have, so it took some time to dig up some of this data. And Devi moved from Virginia Tech to Georgia Tech, so the server that was hosting a lot of the links was taken down. I think the main link needed to get the interface working is this zip file:
https://drive.google.com/file/d/1FKKQA-Zc88ffmOqIuvomUti7mVxSuAVx/view?usp=sharing

If you need something else, let me know and I can try to find it.

Stan

**Comment by akskuchi** [comment]
Hello Stan,

Thanks for the update and the link.

Closing this for now.

Aditya

**Comment by StanislawAntol** [comment]
It turns out the links were invalid due to hard drive failures and the old lab machines are no longer actively supported. I have removed pages that no longer exist and updated both `site_pngs` .zip file links with Google Drive links.
